// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK5SK_QjnirPS_bZPAQxPs72-c9I-0aEI',
    appId: '1:618604349971:web:387c3fe7138d167dfc8de6',
    messagingSenderId: '618604349971',
    projectId: 'greenscan-be468',
    authDomain: 'greenscan-be468.firebaseapp.com',
    storageBucket: 'greenscan-be468.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPF89YKz1ALTDb5PZndPXNrx5xUEHdpI',
    appId: '1:618604349971:android:570527a628f74542fc8de6',
    messagingSenderId: '618604349971',
    projectId: 'greenscan-be468',
    storageBucket: 'greenscan-be468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUXiplCW0W6id7qyLGjZulOakTWaIDWu0',
    appId: '1:618604349971:ios:3e33f99450bab4b4fc8de6',
    messagingSenderId: '618604349971',
    projectId: 'greenscan-be468',
    storageBucket: 'greenscan-be468.appspot.com',
    iosClientId: '618604349971-hvpbrp3idhejdv88e6teigbm7kblv3un.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUXiplCW0W6id7qyLGjZulOakTWaIDWu0',
    appId: '1:618604349971:ios:739f14a9174a9dbefc8de6',
    messagingSenderId: '618604349971',
    projectId: 'greenscan-be468',
    storageBucket: 'greenscan-be468.appspot.com',
    iosClientId: '618604349971-4a4drq9lj7ldb9mdm0lcjb1vv05lit8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantDiseaseDetection.RunnerTests',
  );
}
